package main

var storyStarters = []string{
	"Alone in my room in the quiet night ",
	"Oh god. I am so horrified, because ",
	"It was a dark and stormy night when ",
	"I woke up and thought to myself ",
	"For todays breakfast I had ",
	"For todays lunch I had ",
	"For todays dinner I had ",
	"Yesterday when I ended the stream I  ",
	"Why is everything has to be ",
	"Once upon a time ",
	"I want to become ",
	"Tomorrow I am planning to ",
	"Tomorrow I have a meeting with ",
	"I really should stop ",
	"I am the best ",
	"Today I watched into the mirror and saw ",
	"I like to imagine that ",
	"I think the reason for ",
	"Yesterday when after the stream I wanted to go to bed I ",
	"Nina told me today that I ",
	"Peppah is so loud, that I couldn't sleep weel at night so I decided to ",
	"I think that ",
	"Tomorrow is the very important day for me ",
	"Today after waking up I was thinking about some deep concepts like what is ",
	"Why is this world so ",
	"I am the god gamer ",
	"No one can change my mind on ",
	"My opinion on ",
	"Thanks for watching, donating, socials credits, thank you - I said after ending yesterday stream but in my mind I was thinking - ",
	"I like to think that you should not think about ",
	"My body is really not designed for ",
}
